"""add role to users and user_id to tasks

Revision ID: 037764b3457e
Revises: 0fce7b76d432
Create Date: 2026-09-07 19:03:34.287237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "037764b3457e"
down_revision: Union[str, Sequence[str], None] = "0fce7b76d432"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("user_id", sa.Integer(), nullable=False, server_default="1")
    )
    op.create_foreign_key("fk_tasks_users", "tasks", "users", ["user_id"], ["id"])
    op.add_column(
        "users", sa.Column("role", sa.String(), nullable=False, server_default="user")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_constraint("fk_tasks_users", "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###
